name: notion_gdocs_integration
description: Integrating Google Docs/Slides/Sheets and Notion.
# version: 0.1.0
# homepage: https://www.example.com
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  googleapis_auth: ^1.1.0
  googleapis: ^2.0.0
  functions_framework: ^0.4.0
  shelf: ^1.0.0

dev_dependencies:
  lints: ^1.0.0
  build_runner: ^2.0.0
  functions_framework_builder: ^0.4.0
  http: ^0.13.0
  test: ^1.15.7
  test_process: ^2.0.0
